apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: age-calc-rolebinding
  namespace: age-calc
subjects:
- kind: User
  name: system:serviceaccount:age-calc:default
roleRef:
  kind: Role
  name: age-calc
  apiGroup: rbac.authorization.k8s.io

