# role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: age-calc
  name: age-calc-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "watch", "list"]

