---
- name: Deploy Docker container for web app
  hosts: webservers
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the Docker image from Docker Hub
      docker_image:
        name: robert1oo/web-app
        source: pull

    - name: Run the Docker container
      docker_container:
        name: web-app
        image: robert1oo/web-app
        state: started
        restart_policy: always
        published_ports:
          - "80:5000"


